### ISSUE TITLE
Deleting From Firestore is always throwing the catch block

### ISSUE THREAD

**Issue by Cadris** [firebase/codelab-friendlychat-web#523]
//Addind The Delete Option
const cross=div.querySelector(".deleteIcon");
cross.addEventListener('click',(e) => {
e.stopPropagation();
let id = e.target.parentElement.getAttribute('id');
console.log("Deleting Message : "+id);
const messReff=firebase.firestore().collection('messages').doc(id);
//db.collection('messages').doc(id).delete();
if (imageUrl) { // If the message is an image.
messReff.get().then(async snapshot => {
var imageReff= await snapshot.data().storageUri;
console.log(imageReff);
return await firebase.storage().ref().child(imageReff).delete();
})
.then(()=>{
alert("Image Deleated Successfully !! ");
})
.catch(()=>{
alert("Sorry Error Occoured :(");
});
}
await messReff.delete().then(()=>{
alert("Message Deleted From Database !! :)");
}).catch(()=>{
alert("Sorry Error Occoured in deleting Message :(");
});
});

It is Always Triggering This code
alert("Sorry Error Occoured :(");
Please Help.

This is the Firestore Rules
// Returns true if the uploaded file is an image and its size is below the given number of MB.
function isImageBelowMaxSize(maxSizeMB) {
  return request.resource.size < maxSizeMB * 1024 * 1024
      && request.resource.contentType.matches('image/.*');
}

service firebase.storage {
  match /b/{bucket}/o {
    match /{userId}/{messageId}/{fileName} {
      allow write: if request.auth != null && request.auth.uid == userId && isImageBelowMaxSize(5);
      allow read;
      allow delete: if request.auth.uid!=null;
    }
  }
}

**Comment by jhuleatt** [comment]
Hi @Cadris, you're looking at your rules for Storage, which is a different product from Firestore. Your Firestore rules can be found here: [https://console.firebase.google.com/u/0/project/_/database/firestore/rules](https://console.firebase.google.com/u/0/project/_/database/firestore/rules)
