### ISSUE TITLE
Why are we deleting a message instead of a token?

### ISSUE THREAD

**Issue by mundane140** [firebase/codelab-friendlychat-web#526]
### Codelab info
[I am following firebase-cloud-functions 9](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#9)
My query is related to the CleanUpTokens function.
### Project setup
I am not using friendlychat-web, I am trying to use the codelab to make modifications in project.

### Problem Description
I am assuming the aim here is to delete FCM tokens but the code for the `cleanUpTokens` suggests that we should delete a message (Snippet for `index.js`). 

`
const deleteTask = admin.firestore().collection('messages').doc(tokens[index]).delete();
`

Probably incorrect code snippet. I am not sure as I started with a [firebase-web codelab](https://codelabs.developers.google.com/codelabs/firebase-web/?authuser=2#10) which suggested that I should check out [firebase-cloud-functions 9](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#9).  I skipped to Step 10 i.e. New message notifications.
Maybe both codelabs are using a different data structures.

### Suggested fix
the line should be changed to:
`
const deleteTask = admin.firestore().collection('fcmTokens').doc(tokens[index]).delete();
`

**Comment by jhuleatt** [comment]
Hi @mundane140, nice catch! 

You're correct, that's a typo in the codelab. The actual code that the codelab is based on uses the `fcmTokens` collection:

https://github.com/firebase/codelab-friendlychat-web/blob/1fd6b40260fbdc46ae37e59d8be299daf3948f7a/cloud-functions/functions/index.js#L127

**Comment by jhuleatt** [comment]
I've republished the codelab with updated code. Can you please close this issue if it looks good to you?

**Comment by mundane140** [comment]
Glad I could help! Closing this one 😄
