### ISSUE TITLE
npm install --save @google-cloud/vision@0.12.0 child-process-promise@2.2.1 +++ seems to not work

### ISSUE THREAD

**Issue by MartinRoesch2** [firebase/codelab-friendlychat-web#539]
### [REQUIRED] Codelab info

https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#8

### [REQUIRED] Project setup

cloud-functions-start

In order to avoid problems I followed the codelab closely

### [REQUIRED] Describe the problem

 

The npm install of step 9 (images moderation) fails

![image](https://user-images.githubusercontent.com/6240412/86004219-400d9b80-ba13-11ea-8d01-d05f99d6f0ee.png)
I try to npm install Cloud Vision and Child Process Promise as described in the codelab.
First I ran the command in the wrong dir, above functions.
Then I cd'd into functions and ran it again. Result: Would not find grpc dir in node_modules.
![image](https://user-images.githubusercontent.com/6240412/86004948-4a7c6500-ba14-11ea-98b1-b20bee0f392a.png)
Then I changed version numbers to latest. Resulted in eight "Unsupported engine ..." warnings which state that they want node >=10
![image](https://user-images.githubusercontent.com/6240412/86005246-a8a94800-ba14-11ea-849f-035daad9cefd.png)

**Comment by samtstern** [comment]
@MartinRoesch2 it looks like the libraries require Node 10+ but you're using Node 8.  I would suggest upgrading.

Also @kroikie is the linked codelab still supported?  If so is there a repo for it where I could transfer this issue?

**Comment by MartinRoesch2** [comment]
Thx, I'll try upgrading

**Comment by jhuleatt** [comment]
This is fixed by #648
