### ISSUE TITLE
Step 9 (Image Moderation) - TypeError: Vision is not a constructor

### ISSUE THREAD

**Issue by hirosan1** [firebase/codelab-friendlychat-web#586]
### Codelab info
Cloud Functions for Firebase [Step 9](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/index.html?index=..%2F..index#8)

### Project setup
node version v14.12.0
npm version 6.14.11
google-cloud/vision version 2.3.0

### Describe the problem
Please see [@JamesVanWaza's description](https://github.com/googleapis/nodejs-vision/issues/272#issuecomment-659718237)

>let us know which directory of friendlychat-web you're using, as well as any other relevant details:

I am using _/cloud-functions-start/_ directory

>Is it a grammatical error, incorrect code snippet, or are you running into an unknown bug?: 

Incorrect/outdated code snippet

### Suggested fix
Use
```
const Vision = require('@google-cloud/vision');
const vision = new Vision.ImageAnnotatorClient();
. . .
```
instead of

```
const Vision = require('@google-cloud/vision');
const vision = new Vision();
. . .
```

**Comment by jhuleatt** [comment]
Hi @hirosan1, thanks for reporting this. I'm working on a PR (#596) and update to the codelab to correct this code.
