### ISSUE TITLE
Deploying functions is not possible in Spark plan anymore.

### ISSUE THREAD

**Issue by pikoscielniak** [firebase/codelab-friendlychat-web#603]
Please update code lab [Cloud Functions for Firebase ](https://firebase.google.com/codelabs/firebase-cloud-functions). Deploying functions is not possible in free Spark plan anymore. When I deploy functions with the command `firebase deploy --only functions` I get the message: _Your project xxx must be on the Blaze (pay-as-you-go) plan to complete this command. Required API cloudbuild.googleapis.com can't be enabled until the upgrade ..._. This is known issue as I found about it here https://github.com/firebase/functions-samples/issues/764. But I think it would be nice to find out about the need of upgrade in the lab itself.

**Comment by jhuleatt** [comment]
The codelab now shows the need for the Blaze plan in the "what you'll need section": 

> <img width="759" alt="Screen Shot 2021-11-23 at 1 34 14 PM" src="https://user-images.githubusercontent.com/3759507/143083738-eaa5e1e5-8cc3-443e-95f2-dc87bc9f254c.png">


and the "Create a Firebase project" section:


> <img width="1074" alt="Screen Shot 2021-11-23 at 1 33 49 PM" src="https://user-images.githubusercontent.com/3759507/143083722-9990824b-9336-4f67-ac38-21a05341af1c.png">
