### ISSUE TITLE
Node version not consistent between github and codelab

### ISSUE THREAD

**Issue by pm-mic** [firebase/codelab-friendlychat-web#606]
On this particular page: 
https://firebase.google.com/codelabs/firebase-cloud-functions?authuser=0#5

This is mentioned: 
> By default Cloud Functions runs your code in a Node 6 runtime. We've changed this to the Node 8 runtime which is in Beta by specifying it in the package.json file by adding: "engines": { "node": "8" }

In the current "package.json" file the engine is defined like this: 
`  "engines": {
    "node": "12"
  },`

**Comment by samtstern** [comment]
@pm-mic thanks for reporting this! I'll get it fixed.
