### ISSUE TITLE
MacOS Monterey uses port 5000 for Airplay Receiver

### ISSUE THREAD

**Issue by Drblessing** [firebase/codelab-friendlychat-web#653]
### Codelab info

[Firebase web codelab - step 5](https://firebase.google.com/codelabs/firebase-web#4) 

### Project setup

Directory: `web-start` 
Operating System: macOS Monterey Version 12.2

### Describe the problem

 
The Airplay Receiver sharing functionality uses port 5000 and is enabled by default. Therefore, the command `firebase serve --only hosting` does not work, and going to it, the user will receive the HTTP error 403 Forbidden. 

### Suggested fix
Serve it on a different port. For instance: `firebase serve --only hosting --port 5005` and then try the app on [http://localhost:5005](http://localhost:5005). You can also disable Airplay Receiver, and it will work as intended.

**Comment by clwest** [comment]
Thank you!

**Comment by jhuleatt** [comment]
Thanks for posting a workaround @Drblessing! The Firebase CLI can now detect this issue and automatically pick another port, starting in version [`10.7.0`](https://github.com/firebase/firebase-tools/releases/tag/v10.7.0) (if you're interested in the specifics of the fix, take a look at https://github.com/firebase/firebase-tools/pull/4415).

**Comment by Drblessing** [comment]
Thanks!

**Comment by nickjuntilla** [comment]
Interesting I'm using firebase cli 12.9.1 and it still fails silently.
