### ISSUE TITLE
Broken link for Google Cloud - Cloud Vision API

### ISSUE THREAD

**Issue by luismartinezs** [firebase/codelab-friendlychat-web#659]
In this step of the Firebase Cloud Functions codelab:

https://firebase.google.com/codelabs/firebase-cloud-functions?authuser=0#8

Under the heading Enable the Cloud Vision API, there is a link to this URL: https://console.cloud.google.com/apis/api/vision.googleapis.com/overview?project=_&authuser=0

When I open this link in my browser (Chrome) there is a redirect to a very long path and the navigation gets stuck.

I suggest replacing the link href by: https://console.cloud.google.com/apis/api/vision.googleapis.com/overview?authuser=0

**Comment by thatfiredev** [comment]
@luismartinezs good catch! Thanks for opening this issue. I have filed this internally and will update this issue once it has been fixed.

---
Googlers: For reference, the long path mentioned here is: `https://console.cloud.google.com/projectselector2/projectselector2/projectselector2/projectselector2/projectselector2/projectselector2/[repetition omitted]/apis/api/vision.googleapis.com/overview?project=_&authuser=0&supportedpurview=project`

Addressing this in [cl/450387858](http://cl/450387858)

**Comment by thatfiredev** [comment]
@luismartinezs Thanks for reporting this error. It has been fixed now :)
