### ISSUE TITLE
Cannot run the starter app locally

### ISSUE THREAD

**Issue by albinsopaj** [firebase/codelab-friendlychat-web#694]
### Codelab info

https://firebase.google.com/codelabs/firebase-web?hl=en#0

### Project setup

I'm using the web-start directory.

### Describe the problem

 
The problem I've encountered is that I'm not able to Run the Starter App locally. I followed all instructions, but when I open http://localhost:5000, it simply says Cannot GET. I'm not able to see FriendlyChat app's UI. I'm hoping that the codelabs aren't outdated.

![Screenshot 2022-10-18 120858](https://user-images.githubusercontent.com/62503305/196401880-bb20a3d2-6d20-4347-a3e2-4d5043703068.png)

**Comment by gautedl** [comment]
In firebase.json change "public" to "public": "./public/index.html",

**Comment by fjuren** [comment]
Does specifying the path like this solve the problem though? Seems like you run into more errors / issues, unless I'm missing something.
