### ISSUE TITLE
https-static.xx.fbcdn.net-rsrc.php-v3-yL-r-unHwF9CkMyM.png- Facebook messenger

### ISSUE THREAD

**Issue by brian2269** [firebase/codelab-friendlychat-web#722]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by onff66** [comment]
data:text/css; charset=utf-8,.ew7X7bE.ew7X7bE%7Bdisplay%3Anone%7D%0A

**Comment by onff66** [comment]
data:text/css; charset=utf-8,.ew7X7bE.ew7X7bE%7Bdisplay%3Anone%7D%0A
